### ISSUE TITLE
Question about mAP evaluation on TAL task

### ISSUE THREAD

**Issue by sming256** [sudo-Boris/mr-Blip#1]
Thanks for your amazing work! I have two questions regarding your implementation on the TAL task.

1. The TAL tasks require the model not only to predict the start/end times of candidate predictions but also the action category. However, in Mr.Blip, the action category is provided as known information in the text prompt on TAL. I wonder, is this appropriate?
2. When I use your released checkpoint to infer on TAL, I can reproduce your results, which is around 51.11 mAP under this codebase. However, when I use the predicted JSON file `val_epochbest.json` and evaluate it under other standard TAL evaluation code, such as [here](https://github.com/happyharrycn/actionformer_release/blob/main/libs/utils/metrics.py) and [here](https://github.com/sming256/OpenTAD/blob/main/opentad/evaluations/mAP.py), I can only get **25.93% mAP**. This indicates a difference between your implementation and previous TAL implementations. Can you check what the issue might be to ensure the correct evaluation on the TAL task?

The output file from Mr.Blip I use is [val_epochbest.json](https://github.com/user-attachments/files/16075018/val_epochbest.json), and the converted JSON file (combined with the GT category) is [mrblip_converted_detection.json](https://github.com/user-attachments/files/16074988/mrblip_converted_detection.json).
The following is the evaluation result.
```
Number of predictions: 5115
Fixed threshold for tiou score: [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
Average-mAP: 25.93 (%)
mAP at tIoU 0.50 is 41.20%
mAP at tIoU 0.55 is 37.96%
mAP at tIoU 0.60 is 35.12%
mAP at tIoU 0.65 is 32.25%
mAP at tIoU 0.70 is 29.06%
mAP at tIoU 0.75 is 25.80%
mAP at tIoU 0.80 is 21.81%
mAP at tIoU 0.85 is 17.25%
mAP at tIoU 0.90 is 12.40%
mAP at tIoU 0.95 is 6.45%
```

**Comment by sudo-Boris** [comment]
Hi @sming256, thank you for the feedback!

1. You are right. Assuming the action class as given and using it as input is a mistake. I sincerely apologize for overlooking this (significant) detail... I have already updated the leaderboard on Papers with code, will update the code base accordingly, rerun the experiments under the correct TAL setting, and report the updated numbers. 
2. For the mAP implementation, I leverage the official implementation for [QVHighlights](https://github.com/jayleicn/moment_detr/blob/main/standalone_eval/eval.py). Since the TAL task is different, and requires a different mAP implementation, the reported numbers will be wrong/ not comparable.

I misunderstood the TAL task when reading the [UnLoc paper](https://openaccess.thecvf.com/content/ICCV2023/papers/Yan_UnLoc_A_Unified_Framework_for_Video_Localization_Tasks_ICCV_2023_paper.pdf) and now understood what they did when looking deeper into their code.

I sincerely apologize for this mistake...

Thank you for pointing it out!

**Comment by sming256** [comment]
Thank you for your quick reply! 
I appreciate your clarification, and I am amazed by the results on the other moment retrieval tasks. Great work!

**Comment by sudo-Boris** [comment]
Thank you very much!
We will hopefully soon be able to report the correct numbers on TAL :)

**Comment by sudo-Boris** [comment]
We have updated the paper and will soon update the code base!
Thank you for your interest in our work and for pointing out this bug.
