### ISSUE TITLE
inference 

### ISSUE THREAD

**Issue by 1028267022** [sudo-Boris/mr-Blip#4]
can i inference for other video and text

**Comment by sudo-Boris** [comment]
Yes, that would be possible. 
You would need to format the data correctly. The feature for simple inference providing a video and a query has not been implemented yet.
Just be aware of which model you want to use since there might be a domain gap between the training data and the sample on which you want to make test-time inferences.

**Comment by 1028267022** [comment]
where could i find the feature  extraced code?
