### ISSUE TITLE
About testing in charades-sta

### ISSUE THREAD

**Issue by josephzpng** [sudo-Boris/mr-Blip#6]
Great job! Thank you for your open source. 
When I reproduced charades-sta, I used the data processing script and checkpoint you provided, but the test results did not meet the expected results of the paper, and the final results would change with the change of batchsize. What is the problem and how to solve it? Looking forward to your reply!

**Comment by sudo-Boris** [comment]
Sorry for the late response!
The performance is indeed fairly sensitive to the training hyperparameters.
We still have the logs of the past runs that achieved the reported results but since we ran those experiments we did slight modifications to the model implementation, and are looking into what the changes were that decrease the performance on charades.

Really sorry for this potentially unsatisfactory response!

**Comment by sudo-Boris** [comment]
Sorry for the long wait, but we finally found and fixed the small bug. The performance of our models, when evaluated, should now be as reported (within the bounds of some small variance).

Please feel free to reopen the issue if there is still an issue. Thank you for your patience!
