### ISSUE TITLE
Very bad results on Charades

### ISSUE THREAD

**Issue by fake-warrior8** [sudo-Boris/mr-Blip#8]
I used the charades splits from [MMN](https://github.com/MCG-NJU/MMN/tree/main/dataset/Charades_STA) to implement the results, train/val splits follow your code.  The R1@0.5, R1@0.7, mIoU are 63.8 42.1 54.77 , which are -3.9, -5.5, -7.2 compared to the paper results of 69.31, 49.29, 58.63

My reimplemented QVHighlight results:  R1@0.5, R1@0.7, mAP@0.5, mAP@0.75 are 76.39, 62.32, 68.92, 54.94, which are +0.3, -1.0, -0.5, -0.8 compared to your paper results.

**Comment by 0E0W-AC** [comment]
the same question

**Comment by sudo-Boris** [comment]
Sorry for the late response!
The QVH results seem to be within the expected variance, but the Charades numbers are indeed far too low. We still have the logs of the past runs that achieved the reported results but since we ran those experiments we did slight modifications to the model implementation, and are looking into what the changes were that decrease the performance on charades this drastically.

Really sorry for this potentially unsatisfactory response!

**Comment by ki-lw** [comment]
hi author，so do you find the key change now?

**Comment by sudo-Boris** [comment]
> hi author, so do you find the key change now?

We managed to recreate the results but are still updating the codebase.
Very sorry for the slow progress!

**Comment by ki-lw** [comment]
Hi author, when will the repository be ready for implementing the best results？

**Comment by sudo-Boris** [comment]
Sorry for the long wait, but we finally found and fixed the small bug. The performance of our models, when evaluated, should now be as reported (within the bounds of some small variance).

Please feel free to reopen the issue if there is still an issue. Thank you for your patience!
